# Generated by Django 5.2.9 on 2026-06-04 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "cedula",
                    models.CharField(max_length=20, unique=True, verbose_name="Cédula"),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                ("direccion", models.TextField(blank=True, verbose_name="Dirección")),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.CreateModel(
            name="Entrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Entrada"
                    ),
                ),
                (
                    "modelo_maquina",
                    models.CharField(
                        max_length=100, verbose_name="Modelo de la Máquina"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        verbose_name="Observaciones o Repuestos que lleva"
                    ),
                ),
                (
                    "monto_trabajo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Monto del Trabajo",
                    ),
                ),
                (
                    "monto_repuestos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Monto de los Repuestos",
                    ),
                ),
                (
                    "abono",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Abono"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("en_taller", "En Taller"),
                            ("entregado", "Entregado"),
                        ],
                        default="en_taller",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entradas",
                        to="libreria.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada",
                "verbose_name_plural": "Entradas",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cedula",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Cédula",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("supervisor", "Supervisor"),
                            ("inventario", "Inventario"),
                            ("consulta", "Consulta"),
                            ("soporte", "Soporte"),
                            ("parque", "Parque"),
                        ],
                        default="inventario",
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                ("direccion", models.TextField(blank=True, verbose_name="Dirección")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfiles de Usuarios",
            },
        ),
        migrations.CreateModel(
            name="Salida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_entrega",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Entrega"
                    ),
                ),
                (
                    "pago_final",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Pago Final Realizado",
                    ),
                ),
                (
                    "observaciones_entrega",
                    models.TextField(
                        blank=True, verbose_name="Observaciones de Entrega"
                    ),
                ),
                (
                    "entrada",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salida_rel",
                        to="libreria.entrada",
                        verbose_name="Entrada Asociada",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Entregado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salida",
                "verbose_name_plural": "Salidas",
                "ordering": ["-fecha_entrega"],
            },
        ),
    ]
