# Generated by Django 5.2.9 on 2026-06-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="forma_despacho",
            field=models.CharField(
                choices=[("delivery", "Delivery"), ("en_tienda", "En Tienda")],
                default="en_tienda",
                max_length=20,
                verbose_name="Forma de Despacho",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cedula",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Cédula o RIF"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nombre",
            field=models.CharField(max_length=100, verbose_name="Razón Social"),
        ),
        migrations.AlterField(
            model_name="perfilusuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("supervisor", "Supervisor"),
                    ("soporte", "Soporte"),
                ],
                default="inventario",
                max_length=20,
                verbose_name="Rol",
            ),
        ),
    ]
