# Generated by Django 5.2.9 on 2026-06-29 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0002_cliente_forma_despacho_alter_cliente_cedula_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entrada",
            name="modelo_maquina",
        ),
        migrations.AddField(
            model_name="entrada",
            name="cliente_presente",
            field=models.BooleanField(
                default=False, verbose_name="¿Cliente está presente?"
            ),
        ),
        migrations.CreateModel(
            name="Maquina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modelo", models.CharField(max_length=100, verbose_name="Modelo")),
                (
                    "serial",
                    models.CharField(blank=True, max_length=100, verbose_name="Serial"),
                ),
                (
                    "entrada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maquinas",
                        to="libreria.entrada",
                        verbose_name="Entrada Asociada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Máquina",
                "verbose_name_plural": "Máquinas",
            },
        ),
    ]
