# Generated by Django 5.2.9 on 2026-06-29 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0003_remove_entrada_modelo_maquina_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entrada",
            name="monto_repuestos",
        ),
        migrations.RemoveField(
            model_name="entrada",
            name="monto_trabajo",
        ),
        migrations.CreateModel(
            name="Repuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=150, verbose_name="Nombre del Repuesto"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Valor"
                    ),
                ),
                (
                    "entrada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repuestos",
                        to="libreria.entrada",
                        verbose_name="Entrada Asociada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Repuesto",
                "verbose_name_plural": "Repuestos",
            },
        ),
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=150, verbose_name="Nombre del Servicio"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Valor"
                    ),
                ),
                (
                    "entrada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicios",
                        to="libreria.entrada",
                        verbose_name="Entrada Asociada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio",
                "verbose_name_plural": "Servicios",
            },
        ),
    ]
