# Generated by Django 5.2.9 on 2026-06-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0004_remove_entrada_monto_repuestos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrada",
            name="forma_pago_abono",
            field=models.CharField(
                choices=[
                    ("efectivo", "Efectivo"),
                    ("pago_movil", "Pago Móvil"),
                    ("transferencia", "Transferencia"),
                    ("zelle", "Zelle"),
                ],
                default="efectivo",
                max_length=50,
                verbose_name="Forma de Pago del Abono",
            ),
        ),
        migrations.AddField(
            model_name="entrada",
            name="modalidad_pago_restante",
            field=models.CharField(
                choices=[
                    ("un_abono", "En un solo abono"),
                    ("dos_abonos", "En dos abonos extras"),
                ],
                default="un_abono",
                max_length=50,
                verbose_name="Modalidad Pago Restante",
            ),
        ),
        migrations.AddField(
            model_name="entrada",
            name="tasa_dia",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Tasa del Día"
            ),
        ),
        migrations.AddField(
            model_name="salida",
            name="forma_pago_salida",
            field=models.CharField(
                choices=[
                    ("efectivo", "Efectivo"),
                    ("pago_movil", "Pago Móvil"),
                    ("transferencia", "Transferencia"),
                    ("zelle", "Zelle"),
                ],
                default="efectivo",
                max_length=50,
                verbose_name="Forma de Pago",
            ),
        ),
        migrations.AddField(
            model_name="salida",
            name="tasa_dia_salida",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Tasa del Día"
            ),
        ),
    ]
