# Generated by Django 5.2.9 on 2026-06-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0005_entrada_forma_pago_abono_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrada",
            name="abono_extra",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Abono Extra"
            ),
        ),
        migrations.AddField(
            model_name="entrada",
            name="forma_pago_abono_extra",
            field=models.CharField(
                choices=[
                    ("efectivo", "Efectivo"),
                    ("pago_movil", "Pago Móvil"),
                    ("transferencia", "Transferencia"),
                    ("zelle", "Zelle"),
                ],
                default="efectivo",
                max_length=50,
                verbose_name="Forma de Pago del Abono Extra",
            ),
        ),
        migrations.AddField(
            model_name="entrada",
            name="tasa_dia_abono_extra",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Tasa del Día (Abono Extra)",
            ),
        ),
    ]
