# Generated by Django 5.2.9 on 2026-06-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "libreria",
            "0006_entrada_abono_extra_entrada_forma_pago_abono_extra_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="salida",
            name="garantia",
            field=models.TextField(blank=True, verbose_name="Garantía"),
        ),
    ]
