# Generated by Django 5.2.9 on 2026-06-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0007_salida_garantia"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrada",
            name="observacion_extra",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observación Extra"
            ),
        ),
        migrations.AlterField(
            model_name="entrada",
            name="forma_pago_abono",
            field=models.CharField(
                choices=[
                    ("efectivo", "Efectivo"),
                    ("pago_movil", "Pago Móvil"),
                    ("transferencia", "Transferencia"),
                    ("zelle", "Zelle"),
                    ("t_debito", "T. Débito"),
                ],
                default="efectivo",
                max_length=50,
                verbose_name="Forma de Pago del Abono",
            ),
        ),
        migrations.AlterField(
            model_name="entrada",
            name="forma_pago_abono_extra",
            field=models.CharField(
                choices=[
                    ("efectivo", "Efectivo"),
                    ("pago_movil", "Pago Móvil"),
                    ("transferencia", "Transferencia"),
                    ("zelle", "Zelle"),
                    ("t_debito", "T. Débito"),
                ],
                default="efectivo",
                max_length=50,
                verbose_name="Forma de Pago del Abono Extra",
            ),
        ),
        migrations.AlterField(
            model_name="salida",
            name="forma_pago_salida",
            field=models.CharField(
                choices=[
                    ("efectivo", "Efectivo"),
                    ("pago_movil", "Pago Móvil"),
                    ("transferencia", "Transferencia"),
                    ("zelle", "Zelle"),
                    ("t_debito", "T. Débito"),
                ],
                default="efectivo",
                max_length=50,
                verbose_name="Forma de Pago",
            ),
        ),
    ]
