# Generated by Django 5.2.9 on 2026-06-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0008_entrada_observacion_extra_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entrada",
            name="observacion_extra",
        ),
        migrations.AddField(
            model_name="entrada",
            name="observacion_pago",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observación del Pago"
            ),
        ),
    ]
