# Generated by Django 5.2.9 on 2026-06-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0009_remove_entrada_observacion_extra_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrada",
            name="observacion_abono_extra",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observación del Abono Extra"
            ),
        ),
    ]
