# Generated by Django 5.2.9 on 2026-07-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0010_entrada_observacion_abono_extra"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrada",
            name="fecha_abono_extra",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha del Abono Extra"
            ),
        ),
        migrations.AddField(
            model_name="entrada",
            name="fecha_abono_inicial",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha del Abono Inicial"
            ),
        ),
        migrations.AddField(
            model_name="repuesto",
            name="cantidad",
            field=models.PositiveIntegerField(default=1, verbose_name="Cantidad"),
        ),
        migrations.AddField(
            model_name="servicio",
            name="cantidad",
            field=models.PositiveIntegerField(default=1, verbose_name="Cantidad"),
        ),
        migrations.AlterField(
            model_name="salida",
            name="fecha_entrega",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Entrega"
            ),
        ),
    ]
