# Generated by Django 5.2.9 on 2026-07-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0011_entrada_fecha_abono_extra_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salida",
            name="observacion_pago_final",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observación del Pago Final"
            ),
        ),
    ]
